---
- name: download repo puppet para debian
  get_url:
   url: http://apt.puppetlabs.com/puppet5-release-xenial.deb
   dest: /tmp/puppet.deb
  when: ansible_os_family == "Debian"

- name: instala o repositorio no debian
  apt:
   deb: /tmp/puppet.deb
  when: ansible_os_family == "Debian"

- name: download repo puppet para redhat
  get_url:
   url: http://yum.puppet.com/puppet5/puppet5-release-el-7.noarch.rpm
   dest: /tmp/puppet.rpm
  when: ansible_os_family == "RedHat"

- name: instala o repositorio no redhat
  yum:
   name: /tmp/puppet.rpm
  when: ansible_os_family == "RedHat"

- name: instalando puppet agent
  apt:
   name: puppet-agent
   update_cache: yes
   state: present
  when: ansible_os_family == "Debian"

- name: instalando puppet agent RedHat
  yum:
    name: puppet-agent
    state: present
  when: ansible_os_family == "RedHat"
