---
- name: download repo puppet
  get_url:
   url: http://apt.puppetlabs.com/puppet5-release-xenial.deb
   dest: /tmp/puppet.deb
  when: ansible_hostname == "devops"

- name: instala o repositorio
  apt:
   deb: /tmp/puppet.deb
  when: ansible_hostname == "devops"
